### ISSUE TITLE
Make executable scripts FreeBSD-compatible by default.

### ISSUE THREAD

**Issue by breakone9r** [theixle/aardwolf-tintin#8]
Two things are necessary:
add bash to the requirements list, as FreeBSD does NOT include bash by default.
change the bangs of every script to
#!/usr/bin/env bash

Because bash is ALSO installed into /usr/local/bin/bash on BSD. since it's NOT an included program. ALL 3rd party programs go into /usr/local on FreeBSD, while root and /usr/ are STRICTLY for apps that are part of the OS itself.

Thanks

**Comment by theixle** [comment]
Sure. Why not.

**Comment by theixle** [comment]
I think this should be done. Looked like it was just 'tmuxit' and 'pmuxit' tmux scripts that needed to be updated and added a mention of bash to requirements. Let me know if you see anything else. Thanks!
