### ISSUE TITLE
Changed the quest.tin file to output the quest info into a file rather than into a group.

### ISSUE THREAD

**Issue by breakone9r** [theixle/aardwolf-tintin#9]
Feel free to look it over and include the changes if you wish. It will sync nicely with your existing tmuxit script since it actually creates the file that script is looking for :)

[quest.zip](https://github.com/theixle/aardwolf-tintin/files/1290505/quest.zip)

**Comment by breakone9r** [comment]
oops. forgot to enclose the Quest Requested event response in brackets.

**Comment by KirkF** [comment]
Can you make this a pull request? I don't know if this repo is still maintained but even if it's forked it would be good to attribute authorship to you

**Comment by breakone9r** [comment]
i just now noticed this, @KirkF. honestly, at this point, i dont even remember what I did, or why I did it, lol. credit or no. public domain the heck out of that little snippet, idc. :)
